### ISSUE TITLE
publish to NPM

### ISSUE THREAD

**Issue by max-mapper** [cubehero/stljs#1]
hi! I'd like to use this and was wondering if you were still maintaining it and if so could put it on NPM

**Comment by talpadk** [comment]
It is probably still used on cubehero.com for rendering static images of STL files...

**Comment by iamwilhelm** [comment]
Hi, sorry I didn't notice this issue here until now. Somehow github didn't send me email about this.

I just refactored the entire library, cleaned it up, and published it onto npm as "stljs". It no longer depends on the c lib, stl2pov, and it now can read ASCII and Binary STL files.

So you should be able to clone it and use it.
